DROP TABLE IF EXISTS `netplix`.`users`;
CREATE TABLE `netplix`.`users`(
    USER_ID VARCHAR(255) NOT NULL COMMENT '사용자 ID (UUID)',
    USER_NAME VARCHAR(50) NOT NULL COMMENT '사용자 이름',
    PASSWORD VARCHAR(255) NOT NULL COMMENT '사용자 비밀번호 (암호화)',

    CREATED_AT DATETIME NOT NULL COMMENT '생성일자',
    CREATED_BY VARCHAR(50) NOT NULL COMMENT '생성자',
    MODIFIED_AT DATETIME NOT NULL COMMENT '수정일자',
    MODIFIED_BY VARCHAR(50) NOT NULL COMMENT '수정자',

    PRIMARY KEY (USER_ID)
);